# Generated by Django 6.0 on 2025-12-07 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tagline', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='companies/')),
                ('website_url', models.URLField(blank=True)),
                ('features', models.TextField(help_text='Enter features separated by commas')),
            ],
            options={
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('author_initials', models.CharField(help_text='e.g. JD', max_length=5)),
                ('bg_color', models.CharField(default='#e0f2f1', help_text='Hex code or color name', max_length=20)),
            ],
        ),
    ]
